server:
    http:
        addr: 0.0.0.0:8000
        timeout: 10s
        corsAllowOrigins: ["*"]
    grpc:
        addr: 0.0.0.0:9000
        timeout: 10s

data:
    database:
        maxOpenConns: 100
        maxIdleConns: 100
        connMaxLifetime: 60
        driver: postgresql
        database: univer
        dsn: host=host.docker.internal port=5432 dbname=univer user=postgres password=Phuc3724@ sslmode=disable TimeZone=Asia/Ho_Chi_Minh
        replicaDSN:
    rabbitmq:
        enabled: true
        addr: amqp://guest:guest@univer-rabbitmq:5672/
        eventSync: false
        cluster:
            enabled: false
            username: ""
            password: ""
            addr: ""
            vhost: ""
            schema: "amqp"
    temporal:
        addr: univer-temporal:7233
        namespace: default
    redis:
        poolSize: 100
        addr: "univer-redis:6379"
        db: 0
        username: ""
        password: ""
        read_timeout: 1s
        write_timeout: 1s
    s3:
        accessKeyID: "minio"
        accessKeySecret: "minio123456"
        region: "us-east-1"
        endpoint: "http://univer-minio:9000"
        endpointPublic: ""
        usePathStyle: true
        presignExpires: 3600s
        defaultBucket: "univer"

service:
    apply:
        addr: collaboration-envoy:10000
        timeout: 10s
    ssc:
        addr: "ssc-server:5005"
        timeout: 10s
admin: []
extra:
    celldataMaxSize: 10485760 # 10M bytes
auth:
    enabled: false
    univerEnabled: false
    cookieDomain:
    oidc:
        enabled: false
        issuer:
        clientID:
        clientSecret:
        redirectURL:
        cookieDomain:
    permission:
        enabled: false
        defaultShareScope: ""
        defaultShareRole: ""
        enableObjInherit: false
        customerStrategies:
apiLimit: {}
sentryConfig: {}
dataProtectionConf:
    enableProtection: false
    dataKeyRotate: 5s
    dataKeyCacheExpiration: 30s
sesConfig: {}
usip:
    enabled: true
    uri:
        credential: http://host.docker.internal:3001/usip/credential
        userinfo: http://host.docker.internal:3001/usip/userinfo
        role: http://host.docker.internal:3001/usip/role
        collaborators: http://host.docker.internal:3001/usip/collaborators
        unitEditTime:
postHogConf:
    enabled: false
entitlementConf:
    enable: false
statsConf: {}
permissionBasedExport:
    enabled: true
